server:
  port: 8088
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: uq pay demo
  mvc:
    view:
      prefix: /
      suffix: .jsp
logging:
  config: classpath:log4j2.xml